version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # command: 'gunicorn --reload --bind 0.0.0.0:5000 webhookApp:app --workers 1 --threads 1 --timeout 60'
    restart: always
    ports:
      - "8000:5000"
    volumes:
      - ./:/app
